# Goal
bool success
string mission_path
bool first
---
# Result
bool mission_done
bool mission_failed
string message
geometry_msgs/Point[] waypoints
float64 turn_degrees
builtin_interfaces/Time stamp
---
# Feedback
string state
