# Goal
string description
sensor_msgs/CompressedImage[] images
---
# Result
string message
geometry_msgs/Point[] waypoints
float64 turn_degrees
builtin_interfaces/Time stamp
---
# Feedback
string state
